[package]
name = "ariacompute-graph"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Aria zero-copy compute graph"

[lib]
name = "aria_graph"

[dependencies]
ariacompute-kernel = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
